### ISSUE TITLE
PDS member files are opened in read only mode.

### ISSUE THREAD

**Issue by johntgatesjr** [IBM/zopeneditor-about#368] opened 2023-11-29 22:27 UTC
## Development environment used

- VS Code 1.84.2
- Z Open Editor version:  3.3.2
- Zowe Explorer: 2.12.2 configured to use z/OSMF to z/OS 3.4
- Editor Platform
  - [x ] Visual Studio Code 1.84.2
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):  MAC/OS 13.6.2
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):  Semaru
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

The only way we can edit in VS Code is to open a PDS member and use the editor like ISPF.  Ie.  Enter an I in the left column to add a line above the one we selected.  That works every time, but is not at all the behavior we are looking for.  We were expecting a full screen editing experience.

Detailed steps for reproducing the problem:

1. First step

### Observed behavior

- Open file.  Try to edit anywhere on the screen - edits are ignored.  Enter an I in the left column - line is added above current line and is editable.

### Expected behavior

- Full screen editing.

**Comment by johntgatesjr** [comment] 2023-12-01 22:04
If you've not seen it that must mean it isn't happening.  Sorry to bother you.

**Comment by phaumer** [comment] 2024-02-15 23:39
Closing as we cannot reproduce and do not have enough information.

**Closed by phaumer** 2024-02-15 23:39 UTC
Labels: invalid
