### ISSUE TITLE
Issues Experienced When Attempting to Connect with the Mainframe

### ISSUE THREAD

**Issue by sccosel** [IBM/zopeneditor-about#50] opened 2020-05-11 16:23 UTC
Z Open Editor seems to be very buggy, especially after v0.4.9 was installed.  People are experiencing issues when attempting to connect with the mainframe.  While there seem to be work arounds, many people are confused that their credentials are wrong, etc.  For more detailed info, see the first FAQ, here: https://github.com/openmainframeproject/cobol-programming-course/issues/53

**Comment by phaumer** [comment] 2020-05-11 17:01
Thanks @sccosel. Do you have specific steps for reproducing? Some screen shot of errors? 

There are two VS Code extensions involved here: Zowe Explorer and Z Open Editor. Zowe Explorer is responsible for the interactivity with z/OS. The Z Open Editor is mainly the COBOL editor. It extends Zowe Explorer with RSE capability and we fixed a bug with 0.4.9 that would through errors when the RSE plugin was not installed. So the hope is that now for using Zowe Explorer with z/OSMF there should be no more impact of the Editor on the Explorer. 

If there are usability issues or bugs with the Zowe Explorer then we want to fix it here: https://github.com/zowe/vscode-extension-for-zowe/issues

**Comment by dastagg** [comment] 2020-05-11 17:25
I think it is more an issue with Zowe Explorer then Z Open Editor.

Here is the problem that I see: per the instructions, I installed the Zowe Explorer and the IBM Z Open Editor. I create the zosmf profile then this message pops up:

```
Zowe Explorer was modified for IBM Remote System Explorer API (RSEAPI) support. 
Please, refresh your explorer views to see RSE REST CLI Profiles. 
If you do not have an RSE REST profile then create it via command line and refresh.
```
I don't need a RSE profile to connect using ZOSMF. 
Plus I can't create a RSE connection with Zowe as I can ZOSMF. 
And even if I do use the command line to create a RSE profile, the only thing I can do within VSCode is add it as a secondary profile to the zosmf profile and that doesn't really get me anything.
Plus, I don't think the RSEAPI is installed/configured yet on the system we are using for this program. 

But since that pop-up keeps showing itself, it is somewhat confusing.

**Comment by phaumer** [comment] 2020-05-11 17:48
@dastagg that pop-up was intended to advertise the new capability to our users. We are discussing how we want to do that going forward. Probably it will only show up in a log window.

**Comment by phaumer** [comment] 2020-05-11 17:51
This Zowe Explorer PR we are contributing will allow you to create profiles of other types graphically in the Zowe Explorer: https://github.com/zowe/vscode-extension-for-zowe/pull/717

Another protocol that we implemented in the same way is FTP (for USS):  https://github.com/phaumer/zowe-explorer-ftp-extension

**Comment by dastagg** [comment] 2020-05-11 17:58
Yeah, I can understand wanting to advertise it but for this "Learning Project" it can be confusing.

I'm waiting for the RSEAPI to be installed/configured on this system so I can try some of the scripts I've downloaded and modified to see how that works but ... (as they say, "Good things come to those who wait" ... hopefully)

**Comment by phaumer** [comment] 2020-05-16 01:44
Closing this for now.  I have removed the "annoying" RSE popup in a future release.

**Closed by phaumer** 2020-05-16 01:44 UTC
Labels: question
