### ISSUE TITLE
Z Open Editor should not create Not Found errors on z/OS when searching for include files

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#134] opened 2021-07-05 06:21 UTC
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: (z open editor version 1.2.1 / nodej.js 14.16.0 / Electron 12.0.7 / chrome 89.0.4389.128 )
- Operating System: Windows 10 Enterprise 20H2
- Java Version :  
Java Version: java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description
 Open a pl1 file in vscodium
In the OCS (Operator console Services on the mainframe) serveral warnings are printed, that some member could not be found.
(all includes are in one of 6 datasets)

### Observed behavior

USER   IEC141I 013-18,IGG0191B,USER,IZUFPROC,SYS00006,5D51,ESYS16, 
 XXXXX.XXX.XXXX.COPYBOOK(MEMBER)                                          
 ERROR DESCRIPTION: IEC141I                                              
 An OPEN macro instruction was issued for a partitioned data set. The    
 END ERROR DESCRIPTION: IEC141I   

### Expected behavior

No error messages should show up, 6 mvs datasets are set in the syslib (zopeneditor.propertygroups), these are really needed.

Thanks!

**Comment by gplambert** [comment] 2021-07-06 19:58
Are any of the mvs includes being resolved?  Do you get this message on just this one member or do you get it for many/all?

**Comment by phaumer** [comment] 2021-07-06 20:10
To analyze how property groups are used by the editor we recommend switching the [logger to debug](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html#troubleshooting-using-log-files) and review the messages in the Output window. It will tell you which cli profile is used, which property groups are being searched, and what files it attempts to download. If you attach your log file we can have a look to see if this is related to our editor or a configuration issue.

**Comment by kraabrsg** [comment] 2021-07-07 05:29
@gplambert every include is resolved and it is the same behaviour for every member. 
We need 6 syslib files in "mvs" type propertygroups. So it seems that every include produces these messages. (if the member is found in the fourth syslib pds dataset, it displays the not found messages for the pds 1 to 3 -> at least that is my guess). It is the same also for includes in includes.  So the number of errors it depends on the number of includes. The perfect solution would be that no error messages are shown at all, or can be prevented with a zopeneditor settings options. 

Thank you!

**Comment by phaumer** [comment] 2021-07-07 06:44
Thanks @kraabrsg. Closing as works-as-designed then. As there is no index available that we can use we have to check in each data set in the order it is listed to see if the file exists. If we get an error we move on to the next. The debug log messages are providing aid in showing which data sets will be searched in which order, show the error, and mentioned that it will move on to the next.

**Comment by kraabrsg** [comment] 2021-07-07 06:54
Ok, thanks for commenting back on this, unfortunatly i will have to use at least one pds at the first place, when a change to a copybook is made it will be placed on this personal lib, to show the updated copybook. quite often that is not needed. As far as i know it is not easy to supress this messages in sysmaster (operator console services). I allready made a log file, but uploading sensitive information has to be checked by the security first -> so it is not needed anymore.

**Comment by phaumer** [comment] 2021-07-07 17:19
Let me reopen this one as we perhaps should discuss other ways of looking for files than just generating errors.

**Comment by TimMSbg** [comment] 2021-07-09 06:25
we do have the same issue with messages IEC141I 013-18... maybe it is possible to concat all pds datasets in syslib and let search these concatination for the include member?

**Comment by jguillaumes** [comment] 2023-04-12 06:59
Hello,

Let me post my 5 cents about the issue (that we are also experiencing). 

In my opinion, this is not exclusively a z/Open Editor issue, and should be tackled BOTH in z/OSMF and the editor. Basically, the problem is we cannot use dataset concatenations remotely. So the "problem" _could_ be solved by:

- Changing the zosmf files and datasets API (or adding a new endpoint) so a dataset concatenation can be specified (via a JSON body, maybe?).
- Changing the editor to make use of that API.

That would mimic the way SYSLIB and similar concatenations are handled in the mainframe traditional tooling and, additionally, would reduce the number of network trips.

**Comment by FALLAI-Denis** [comment] 2023-04-12 07:19
Hi,

It seem to me that z/osmf use BPXWDYN internally to access datasets. 
BPXWDYN has a CONCAT function. 
But z/osmf does'nt expose an API to declare a concatenation and reuse it in successives access.

For your information, we use git repositories to access Copybooks and incluses. For us this résolve some of problems of repetitives access to mainframe.

**Comment by jguillaumes** [comment] 2023-04-12 08:52
We plan to do that... in the future, but right now we are still using PDS members.

**Comment by FALLAI-Denis** [comment] 2023-04-12 20:22
> It seem to me that z/osmf use BPXWDYN internally to access datasets. BPXWDYN has a CONCAT function. But z/osmf does'nt expose an API to declare a concatenation and reuse it in successives access.

The dataset name is part of the URI used (the dataset information is not present in the body of the request).

`GET /zosmf/restfiles/ds/[-(<volser>)/]<dataset-name>[(<member-name>)]`

And z/osmf using a REST architecture, it is not supposed to keep information between two calls...

Maybe we could come up with a syntax like this? (only for search of `<member-name>` in a datasets concatenation, and no `-(volser)` specification).

`GET /zosmf/restfiles/ds/<dataset-name-1>,<dataset-name-2>,...,<dataset-name-n>(<member-name>)`

Which would be the equivalent of JCL concatenation:

```
//ddname   DD DISP=SHR,DSN=dataset-name-1
//         DD DISP=SHR,DSN=dataset-name-2
...
//         DD DISP=SHR,DSN=dataset-name-n
```

The character used to separate each dataset name must be valid for an URI/URL, and invalid for a dataset name. 
Characters `,` or `!` seems appropriate for this, (other characters as `:` have a special meaning in an URI/URL).

**Comment by FALLAI-Denis** [comment] 2023-04-12 20:56
> **We found no reason why that S222 is occouring so often, can we somehow prevent that?**

We have same problem... 

Z Open Editor seems to start up to 8 IZUFPROC, 6 immediately abend in S222 after executing request action, (`GET /ds/<data-set-name>(<member-name>)`, `IZUGGTDS completed, RC=0`), some with IEC141I 013-18, other without IEC141I 013-18, and 2 remains active for a long time.

Our system team has associated the SYSOUT output of IZUFPROC with an unholded class, and SDSF is no longer polluted, (outputs are dumped into an execution report management tool).

**Comment by phaumer** [comment] 2023-04-13 00:20
I will contact the z/OSMF team for guidance. 

Previously, they pointed us to this blog post for configuring z/OSMF for use cases such supporting Zowe: https://community.ibm.com/community/user/ibmz-and-linuxone/blogs/hong-liang-zhao1/2020/10/13/tune-zosmf-rest-service

**Comment by phaumer** [comment] 2023-06-15 23:05
We mediated this issue in Z Open Editor v.3.2.0 by addressing 
- (2) with a new setting `zopeneditor.zowe.maximumParallelFileDownloads` that you can set to `1` to download files sequentially again. Max value is `10`. Default is `5`. 
- (3) with a new setting `zopeneditor.zowe.listBeforeDownload` which would make Z Open Editor first check the existence of a file by performing an extra list operation. If the file exist then a second request would fetch the file. As this impacts performance we have disabled this by default.

**Closed by phaumer** 2023-06-15 23:05 UTC
Labels: enhancement

**Comment by johntgatesjr** [comment] 2024-01-10 17:40
We are seeing these errors as well.  While we appreciate the better performance we get from parallel threads we can't tolerate all of the S222 abends and have thus shut them down.  But, this is not the root cause here.  Why are you starting up a TSO address space to respond to each REST call?  There are much better ways to handle this using the TSO gateway.  Just out of curiosity, does the Editor team talk to the IDz team?  We fixed these sorts of issues with TSO interaction literally years ago.  Likewise with included member library lookups which seems to be where alot of this is occurring.

**Comment by phaumer** [comment] 2024-01-10 18:11
@johntgatesjr it is z/OSMF that does this and there are ways to configure z/OSMF to avoid this. However, this is out of scope for us (you could work with z/OS tech support), because we recommend using the RSE API instead of z/OSMF (the same protocol our IDz uses), which implements its REST APIs differently.

**Comment by johntgatesjr** [comment] 2024-01-10 18:15
Not surprised about z/OSMF.  I wish I could get RSE to work for me.  It works great with IDz and is much lighter across the number of z/OS images I need to support.  I just can't get it work.
