### ISSUE TITLE
PROCESS Option functionality lost

### ISSUE THREAD

**Issue by Felix-Braun** [IBM/zopeneditor-about#344] opened 2023-05-16 09:41 UTC
## Development environment used

- Z Open Editor version: v3.1.1
- Editor Platform
  - [x ] Visual Studio Code
- Editor Platform Version: 1.78.2 (user setup)
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):  Windows 10 Enterprise
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here): openjdk version "11.0.3-redhat" 2019-04-16 LTS
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: 7.16.0
  - Node.js version: v18.12.0
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): no

## Problem Description

If there are any *PROCESS or %PROCESS options in a PL/I program, the Extension can't find any References or Definitions. I'm able to open the includes but cant jump to a variable or open any section.
![Screenshot_2023-05-16_11-19-48](https://github.com/IBM/zopeneditor-about/assets/125555172/f5942946-9be3-4be0-88be-b77149fcee74)

**Comment by phaumer** [comment] 2023-05-17 15:51
This is caused by the MAR expecting only two parameters in our code, but it seems there is an optional third one.

**Comment by phaumer** [comment] 2023-07-19 21:39
Fixed in v3.2.1.

**Closed by phaumer** 2023-07-19 21:39 UTC
Labels: bug
