### ISSUE TITLE
The reserved word "NOT" in Cobol

### ISSUE THREAD

**Issue by TheBigFalcon** [IBM/zopeneditor-about#328] opened 2023-03-02 16:39 UTC
- Z Open Editor version:
- Editor Platform
  - [ #] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

Hi,
The reserved word "NOT" in Cobol is not in same color as the rest of the reserved words
<img width="445" alt="image" src="https://user-images.githubusercontent.com/89270773/222493426-ba53c6bb-e1bd-4b2f-9ef4-3e753ec501e5.png">

**Comment by FALLAI-Denis** [comment] 2023-03-11 14:47
Hi,

"not" is declared as an "operator", not a keyword.

![image](https://user-images.githubusercontent.com/63861965/224490016-cf0314c0-976a-477d-bdca-96ade3a49a05.png)

![image](https://user-images.githubusercontent.com/63861965/224490115-234743ba-2377-43ce-896b-bd46085dd8e6.png)

Same as other operators:

![image](https://user-images.githubusercontent.com/63861965/224490313-92bed70e-70ef-4edf-863d-6b23c46d4a9d.png)

Color rendering depends on the active theme. Example with the "Tomorrow Night Blue" theme:

![image](https://user-images.githubusercontent.com/63861965/224490457-5d1e45a2-54fb-4a37-9d98-e141196901ba.png)

For me it's not a bug, but may be an inappropriate textmate category choice.

Still in my opinion, the problem is rather on the categorization of identifiers, which should have the category "variable.cobol" and not "meta.symbol.cobol":

![image](https://user-images.githubusercontent.com/63861965/224490712-32d3bc01-4456-4931-9c1b-d08888c55c0a.png)

![image](https://user-images.githubusercontent.com/63861965/224491003-bdb4e692-490d-495b-844c-cd93a7e26310.png)


![image](https://user-images.githubusercontent.com/63861965/224491102-b1cd6e7e-3da8-449e-90f6-c11d5ab718f3.png)

**Comment by phaumer** [comment] 2023-06-15 22:56
Fixed in Z Open Editor v3.2.0

**Closed by phaumer** 2023-06-15 22:56 UTC
Labels: bug
