### ISSUE TITLE
Finding references in double

### ISSUE THREAD

**Issue by tomasalagoa** [IBM/zopeneditor-about#45] opened 2020-04-29 09:44 UTC
When following the accompanying pdf with instructions on how to use the extension **Find all references** outputs each reference twice to the side tab in VSCode

![cbl](https://user-images.githubusercontent.com/30747159/80582328-652b6100-8a06-11ea-9da4-01061abe8777.png)

**Comment by phaumer** [comment] 2020-04-30 05:48
@tomasalagoa I cannot reproduce it. Does this happen every time you open that file? What if you close all tabs in all VS Code windows, close all the VS Code windows, and then completely exit VS Code and restart it. Does it happen every time right when you open you first program? Does it happen with all the other course sample programs as well?  

Any additional information you can share about your environment? OS, VS Code version, Java version etc.?

**Comment by phaumer** [comment] 2020-04-30 05:48
![image](https://user-images.githubusercontent.com/4391934/80676424-8e320d00-8a6b-11ea-9461-50a426652a11.png)

**Comment by tomasalagoa** [comment] 2020-04-30 09:12
Thank you very much for the reply, I tried your suggestions but then realized I had two versions of java installed, I uninstalled one and it stopped finding every reference twice.

**Comment by phaumer** [comment] 2020-04-30 15:42
I am not sure that is would be caused by that. Looked like a VS Code outline view or LSP glitch to me. Please, let us know if you experience this again.

**Comment by tomasalagoa** [comment] 2020-04-30 16:51
Hello again, I tried opening different files and the same thing occurs, I'll provide more information:

OS: WSL Windows 10
Java: OpenDJK 11
VSCode version: 1.44.2
Extension version: 0.4.9

**Comment by phaumer** [comment] 2020-04-30 18:01
@tomasalagoa I think I have a theory of what is going on and was able to reproduce it once. It is a race condition that could start the language server twice. Until we publish a fix you just have to stop and start the editor.

**Comment by tomasalagoa** [comment] 2020-04-30 18:05
Thank you very much for the reply, I hope your team can fix this soon!

**Comment by phaumer** [comment] 2020-06-12 15:41
This issue was fixed in v0.5.0. Let us know if this works for you.

**Closed by phaumer** 2020-06-12 15:41 UTC
Labels: bug

**Comment by tomasalagoa** [comment] 2020-07-15 09:53
Sorry for the late reply, it's working fine at the moment. Thank you for the fix
