### ISSUE TITLE
Error while editing PL1 program

### ISSUE THREAD

**Issue by przemekherok** [IBM/zopeneditor-about#13] opened 2019-10-29 11:57 UTC
Hi,

**I receive following error when editing a PL1 program:**

[Error - 12.38.23] Request textDocument/documentLink failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:291)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:615)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:588)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:454)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:300)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:168)
Caused by: java.lang.NullPointerException
	at com.ibm.lsp.pl1.core.handlers.DocumentLinkHandler.doGetDocumentLinks(DocumentLinkHandler.java:73)
	at com.ibm.lsp.pl1.core.handlers.DocumentLinkHandler.getDocumentLinks(DocumentLinkHandler.java:52)
	at com.ibm.lsp.pl1.core.PL1LanguageServer.lambda$5(PL1LanguageServer.java:192)
	at com.ibm.lsp.pl1.core.PL1LanguageServer$$Lambda$32.000000001159E960.apply(Unknown Source)
	at com.ibm.lsp.pl1.core.PL1LanguageServer$1.apply(PL1LanguageServer.java:280)
	at com.ibm.lsp.pl1.core.PL1LanguageServer$1.apply(PL1LanguageServer.java:1)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:613)
	... 6 more

**Is there a solution for this issue?**

**Here is mine settings.json**

{
    "files.associations": {
        "*.COBOL*": "cobol",
        "*.COB*": "cobol",
        "*.COBCOPY*": "cobol",
        "*.COPYBOOK*": "cobol",
        "*.COPY*": "cobol",
        "*.PL1*": "pl1",
        "*.PLI*": "pl1",
        "*.INC*": "pl1",
        "*.INCLUDE*": "pl1",
        "*.JCL*": "jcl"
    },
    "zopeneditor.JAVA_HOME": "C:/ibm_sdk80", 
    "zopeneditor.server.memoryAllocation": 1024,
    "zopeneditor.cobol.enableUnreachableCodeWarnings": false,
}

**Comment by phaumer** [comment] 2019-10-29 22:14
@przemekherok do you have a code sample that allows us to reproduce it? Do you see any impact in the editor when this exception happens, i.e. are any editor functions broken after that?

**Comment by przemekherok** [comment] 2019-10-30 06:15
@phaumer it's any program in my workspace so I believe code doesn't matter. When I type anything, the editor slows done and throw this exception.

**Comment by przemekherok** [comment] 2019-10-30 07:31
When I have Toogle Developer Tools on in VS there is more:

/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3551 [[object Object]]Language **client is not ready yet**
$onExtensionRuntimeError @ /C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3551
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:3551 
**Error: Language client is not ready yet**
	at t.LanguageClient.sendNotification (c:\Users\t6410\.vscode\extensions\ibm.zopeneditor-0.3.11\dist\extension.js:10:122549)
	at T.callback (c:\Users\t6410\.vscode\extensions\ibm.zopeneditor-0.3.11\dist\extension.js:10:91621)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:539)
	at t.ExtHostDocuments.$acceptModelSaved (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:537:525)
	at p._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:635:275)
	at p._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:634:971)
	at p._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:633:639)
	at p._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:632:468)
	at _protocol.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:630:691)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at _.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:274)
	at e.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:787:104)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at _.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:181:274)
	at t.PersistentProtocol._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:185:629)
	at _socketDisposables.push._socketReader.onMessage.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:182:824)
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:50:519)
	at p.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:178:588)
	at _register._socket.onData.e (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:177:958)
	at Socket.t (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:187:68)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:283:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by przemekherok** [comment] 2019-10-30 08:57
@phaumer and even with your test workspace from git when I edit cobol or pl1 elements INCLUDES/COPYBOOKS can't be found and I get this message:

Unable to find copybook CUSTCOPY

I think it can be related...

**Comment by phaumer** [comment] 2019-10-30 19:11
What version of Java have you configured for the editor and with how much memory? 
(see https://ibm.github.io/zopeneditor-about/Docs/getting_started.html#configuring-java-for-ibm-z-open-editor)

**Comment by PrasangAPrajapati** [comment] 2019-10-30 19:14
@przemekherok 

Ok, looks like extension has been corrupted. I have some questions: 

1. Which java are you using ? (It should be Java 8 JDK or higher; must have **64 bit**)
2. Why have you added `1024` for `memory allocation` in your `settings.json` ?
3. How many lines of file you have opened in the beginning when you got the issue ?
4. Which `zopeneditor` version are you using in your vscode ?

**Comment by przemekherok** [comment] 2019-10-31 08:08
Hi Prasang

1. IBM 64-bit SDK for Windows, Java Technology Edition, Version 8
2. It's recommended in **Configuring the Java memory allocation** section in the installation guide
3. It was a source file with 1000 lines
4. Current version 0.3.11

**Comment by przemekherok** [comment] 2019-11-04 06:06
Any advises?

Something more I can provide to help you analyze the problem?

**Comment by phaumer** [comment] 2019-11-04 17:06
@przemekherok,  we found a way to reproduce this error and are investigating.

**Comment by phaumer** [comment] 2019-11-06 21:30
Just an update. We do think that have a fix for it. We will do some more testing and we are also waiting for a release window related to legal approvals required. But it will fixed in our next update.

**Comment by przemekherok** [comment] 2019-11-07 06:04
Thanks Peter, sounds perfect! Let me know the release date :)

**Comment by phaumer** [comment] 2019-11-22 02:07
This issue was fixed in version 0.4.1 now available on the VS Code Marketplace.

**Closed by phaumer** 2019-11-22 02:07 UTC
Labels: bug
