### ISSUE TITLE
COBOL: Loading Copy Books from local C Drive Folder Very Slow or stops loading

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#315] opened 2023-02-01 23:24 UTC
### Laptop running Windows 10

**VSCode**
**Version: 1.74.3** (user setup)
Commit: 97dec172d3256f8ca4bfb2143f3f76b503ca0534
Date: 2023-01-09T16:59:02.252Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.17763
Sandboxed: No

**IBM Z Open Editor Version 3.0.1 - 2023/01/18**

Copy Book loading in VS Code Z Open Editor used to be very fast until a recent update. I do not use ZOWE yet, copy books are local. I am not exactly sure which version began slowing down their loading. I thought it may be fixed quickly but it has persisted now for a over a month, maybe 2. Refer to screen shots below for "Unable to find copy book" error message examples.

We have large COBOL programs with many copy books. It is common to have over 100 copy books in a program. It now takes over 5 minutes to load the list of COBOL copy books in many of my programs and that's if it completes loading them at all. Many times it will take a long time to load them and part way through stop and eventually produce related syntax errors in the main code. Previous versions would load these copy books in a few seconds. I am in and out of large programs all day long so it is becoming a little unbearable.

I have a laptop and a workspace located on my local C Drive. As part of the workspace is a COPY folder where all of my copy books are stored. This was by design so there is no cloud or remote drive involved when Z Open Editor needs to find and load copy books so they can load as fast as possible.

## Problem Description

Detailed steps for reproducing the problem:

1. VS Code with source on local hard drive
2. YAML file to point to local C drive copy book source folder
3. Setup VS Code Workspace on local C Drive with a COBOL source folder and a COPY folder for copy books 
5. Open large COBOL source file with over 100 copy books
6. Sometimes in 5 minutes or so eventually loads all copy books but many times stops loading all copy books

### Observed behavior

- All copy books are not loaded and ones that are loaded take an unusually long time

### Expected behavior

- Expect copy books to load very fast, within 10-20 seconds

### YAML file pointing to COPY library for copy book resolution
name: SCEPTRE
description: For IBM Z Open Editor 3.0.0 or newer. SCEPTRE Copybook resolution
version: 3.0.0
author:
  name: AA CORPORATION

propertyGroups:
  - name: cobol-copybooks
    language: cobol
    libraries:
      - name: syslib
        type: local
        locations:
          - "**/COPY"
          - "**/COPYMQ"
  - name: hlasm-includes
    language: hlasm
    libraries:
      - name: syslib
        type: local
        locations:
          - "**/COPYASM"

### Workspace libraries for VS Code on local C drive and subfolder to Workspace folder.
![Workspace on local C Drive](https://user-images.githubusercontent.com/80063515/216185237-1e44f825-2128-4b41-ba44-a2bb4dc817af.jpg)

### Unable to find copy book - error example
![image](https://user-images.githubusercontent.com/80063515/216185948-4c3032b6-c94b-40af-b440-48c30926ddbf.png)

### Copy book exists in COPY folder
![image](https://user-images.githubusercontent.com/80063515/216187851-f6f4dd6b-70b5-4f46-bb79-2a4a8d6e0193.png)

**Comment by davidkcoblentz** [comment] 2023-02-02 00:11
The example in the screen shots above of COBOL source SC1IIAUC has 117 copy book statements and it did not find or load 55 of the 117. Yet I can open each copy book member it says it can't find.

**Comment by davidkcoblentz** [comment] 2023-02-02 00:32
I notice that each time I load the same source module SC1IIAUC it stops loading copy books at different members. This time it took 5 minutes 16 seconds to complete loading the copy books that it could and then had 42 not found. Almost like it is timing out and doesn't try all of them or some error occurs while loading them.
![image](https://user-images.githubusercontent.com/80063515/216200849-cf08f0b2-5690-4449-a960-25ec4bf8676e.png)

**Comment by davidkcoblentz** [comment] 2023-02-02 00:39
Loaded the same source module, this time 4 minutes 15 seconds and unable to find 35 and stopped on a different copybook.

**Comment by FALLAI-Denis** [comment] 2023-02-02 07:12
Hi @davidkcoblentz 

Do you try to increase memory size allocated to Java ? (ZOE user settings).

**Comment by davidkcoblentz** [comment] 2023-02-02 18:17
WOW!!! The difference in changing the YAML file with direct references is night and day! That same module loaded all copy books in less than 2 seconds. I am happy again.

**Comment by davidkcoblentz** [comment] 2023-02-02 18:18
There may be opportunities to re-visit the wildcard option in the ZAPP.YAML file for performance.

**Comment by FALLAI-Denis** [comment] 2023-02-02 18:24
Hi,

Putting absolute paths in a zapp.yaml file gives me trouble...

The zapp.yaml file is included in the Workspace, and in principle in the Git Repository used to create this Workspace.

A priori, the zapp.yaml file is a configuration element of the Git Repository, shared by all developers, which follows branch merges, and has no reason to be modified by a developer in his work context.

We do not control the location where the developer will clone his Git repository, and we cannot put an absolute path in the zapp.yaml file...

**Comment by phaumer** [comment] 2023-02-02 18:35
That is good new. Thanks. The problem is the wildcard evaluation, which takes a long time on slow disks. We have some ideas of improving that by caching the evaluation results. So, you do not need an absolute path, just minimize the search space for wildcards.

**Comment by FALLAI-Denis** [comment] 2023-02-02 19:21
Hi @davidkcoblentz 

Can you make a try with path "COPY" instead of "**/COPY". 

Thanks.

**Comment by davidkcoblentz** [comment] 2023-02-02 19:27
Made the change and it loads all copybooks at sub-second speed. Even faster than before.

**Comment by davidkcoblentz** [comment] 2023-02-02 19:29
Ludicrous Speed....

**Comment by phaumer** [comment] 2023-02-02 20:04
Great news. Thanks @davidkcoblentz. 

We have that caching already tracked somewhere else and still have issue https://github.com/IBM/zopeneditor-about/issues/313 that we are tracking for performance. So I will close this one for now.

**Comment by FALLAI-Denis** [comment] 2023-02-02 20:10
Hi,

In our git repositories, all the elements that participate in the construction are placed in différent subfolders depending on a root folder "src". 
Our zapp.yaml files use paths relative to "src" with a glob, for example "src/**/COPY". 

The same rule applies for example to Sonar, limiting the analysis to "src" and its subfolders.

 I recommand isolate your programming elements in a root folder like "src".

**Comment by davidkcoblentz** [comment] 2023-02-02 20:16
Yes, all of my source is under one folder C:\VS Code Source\SCEPTRE-ISPP-Source-Code. When I was reading the documentation it sounded to me like I didn't need the **SCEPTRE-ISPP-Source-Code** folder so I just put **. Sounds like that was the problem.

**Comment by FALLAI-Denis** [comment] 2023-02-02 20:21
If SCEPTRE-ISPP-Source-Code is the name of your repository, it is outside of the workspace, (workspace start under the folder corresponding to the repository).

**Comment by davidkcoblentz** [comment] 2023-02-02 20:23
![image](https://user-images.githubusercontent.com/80063515/216441420-75381087-7abd-4f5d-9b98-5af8946f7e6c.png)

**Comment by phaumer** [comment] 2023-03-10 00:29
We made some big improvements in Z Open Editor 3.1.0. We tested with a 1000 copybooks distributed in many folders using a complex glob pattern and loading went from 8 minutes down to 4 seconds on a fast Mac.

**Closed by phaumer** 2023-03-10 00:29 UTC
Labels: enhancement

**Comment by davidkcoblentz** [comment] 2023-03-10 17:14
Thanks Peter, that is awesome!!

Thank you,
***@***.***
