### ISSUE TITLE
PL/I Margins

### ISSUE THREAD

**Issue by ThorOlson** [IBM/zopeneditor-about#41] opened 2020-04-20 11:48 UTC
More of a question.  I'm just getting started with this editor under Visual Studio Code.  I normally use Margins(1,200) and keep the source to about 120 characters wide.  When opening existing an program with this editor it immediately flags much of the program as having syntax errors.  Is there any way to override the default widths?  I've been able to the set tabs/rulers but not the syntax check.

**Comment by phaumer** [comment] 2020-04-21 14:50
@ThorOlson thanks for your feedback. I would like to resolve this as a duplicate to Issue #17 as we would like to provide compile options like these for a workspace or user. For now you need to specify the margins in each file in the first line such as 

```pl1
*process MARGINS(2,120);
```

**Comment by phaumer** [comment] 2020-04-21 14:50
Duplicate of #17

**Closed by phaumer** 2020-04-21 14:50 UTC
Labels: duplicate

**Comment by ThorOlson** [comment] 2020-04-21 20:01
Thank you that response was a great help!  I wouldn’t have guessed that the editor was using the process statement.

 

Most of the errors went away with the addition of the margins setting, however there is still a bit of a problem with Margins(1,120) though.  It seems to randomly flag errors if the code starts in column 1.  The errors below go away when the declare starts in column 2…

 

 

 

Thanks,

Thor Olson

**Comment by phaumer** [comment] 2020-04-21 21:09
@ThorOlson yes, that is another known issue. Our editor does not "like" code that starts at 1; nor does IDz which provides our codebase.  For now we require column 2 for reasons that I need to research. I add it for the todos for #17 as well.
