### ISSUE TITLE
WHENEVER SQLERROR GO TO unreachable code symbol

### ISSUE THREAD

**Issue by ClaudeBirtz** [IBM/zopeneditor-about#18] opened 2019-11-19 09:52 UTC
An EXEC SQL WHENEVER SQLERROR GO TO  statement shows the error routine as being unreachable:

![WHENEVER_SQLERROR_1](https://user-images.githubusercontent.com/44015114/69135702-d232e600-0ab9-11ea-8394-3252782fdab1.jpg)

Hovering over the error:

![WHENEVER_SQLERROR_2](https://user-images.githubusercontent.com/44015114/69135730-e1199880-0ab9-11ea-935a-c5c81bcb535c.jpg)

**Comment by phaumer** [comment] 2019-11-21 00:12
@ClaudeBirtz thanks for reporting this. This issue is related to a limitation of analyzing control flow in Embedded SQL statements. We are looking for ways to fix this.

In the meantime, we will switch off all Unreachable Code warnings by default in the next  release as we are concerned about reporting false positives of unreachable code.  Users will be able to switch it back on, though, if they can accept the current limitation, with a User Setting.

**Comment by ClaudeBirtz** [comment] 2019-11-21 09:14
Hello Peter, 

thanks for your answer. The zopeneditor is a very useful tool and I'm looking forward to further releases.

**Comment by FALLAI-Denis** [comment] 2020-04-17 14:34
Hello,

Same issue for "EXEC CICS HANDLE" :

![EXEC CICS HANDLE - Unreachable code](https://user-images.githubusercontent.com/63861965/79580429-44d7da00-80c9-11ea-9a7d-2c494b38bbde.png)

**Comment by phaumer** [comment] 2020-04-21 22:16
@FALLAI-Denis were are not able to reproduce this for CICS HANLE.  Would you have a small self-contained code sample for us that would help us reproducing it?

**Comment by FALLAI-Denis** [comment] 2020-04-22 23:37
Sample COBOL program with "EXEC CICS HANDLE ABEND LABEL(label) END-EXEC.

![ZOEHANDL_Z_Open_Editor](https://user-images.githubusercontent.com/63861965/80043730-cfbe3780-8502-11ea-945a-6d524700daea.png)
[ZOEHANDL_cbl.txt](https://github.com/IBM/zopeneditor-about/files/4519433/ZOEHANDL_cbl.txt)
[ZOEHANDL_translated_cbl.txt](https://github.com/IBM/zopeneditor-about/files/4519436/ZOEHANDL_translated_cbl.txt)

**Comment by phaumer** [comment] 2020-04-23 02:00
Thanks a lot. I was also able to reproduce now (that's why I deleted my earlier comment).

**Comment by phaumer** [comment] 2020-06-12 15:41
This issue was fixed in v0.5.0. Let us know if this works for you.

**Closed by phaumer** 2020-06-12 15:41 UTC
Labels: bug

**Comment by FALLAI-Denis** [comment] 2020-06-12 16:32
Hi
Thanks,
The bug is corrected for EXEC SQL WHENEVER GO TO (issue #18),
but still present for EXEC CICS HANDLE ABEND (issue #52)
