### ISSUE TITLE
Not able to delete job with Zowe RSE profile

### ISSUE THREAD

**Issue by lauren-li** [IBM/zopeneditor-about#77] opened 2020-09-02 19:08 UTC
Original issue filed in Zowe Explorer repo: zowe/vscode-extension-for-zowe#996

## Development environment used

- Z Open Editor version:
- Editor Platform
  - [ ] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here):
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): yes/no

### Observed behavior
From @oakmount66:

> From within VScode I can use my Zowe RSE profile to list Host Datasets, USS datasets and Host jobs. But when I try to delete a job I get an Invalid Credentials message.
> 
> ![image](https://user-images.githubusercontent.com/60236192/91694287-afffe580-eb6c-11ea-93fe-9f533765d192.png)
> 
> When I use my z/OSMF profile a delete works fine.
> 
> ![image](https://user-images.githubusercontent.com/60236192/91694455-d9207600-eb6c-11ea-888c-642c1832a54e.png)
> 
> I do not use SCS and it's the same user/password for the two profiles.
> 
> Zowe CLI version: 6.19.1
> VScode version: 1.48.2
> z/OS version: v2.4

Additional information:

> Just found this in the host log
> 
> ![image](https://user-images.githubusercontent.com/60236192/91698690-6a92e680-eb73-11ea-882a-c7c604a15cf6.png)
> 
> Be aware that in our code page $ is a Å

### Expected behavior

- Ability to delete a job with Zowe RSE profile in Zowe Explorer.

**Comment by lauren-li** [comment] 2020-09-02 19:47
@oakmount66 Do you have the RSE CLI plugin installed? If so, could you please try running the command to delete a job from there and see if it works?:

`zowe rse delete job <JOBID>`

(Replace `<JOBID>` with the actual Job ID.)

**Comment by oakmount66** [comment] 2020-09-03 14:19
Yes I have. And I get the same error.

![image](https://user-images.githubusercontent.com/60236192/92127017-2c125b80-ee01-11ea-9fd0-7ae79c66a331.png)

And in the host log

![image](https://user-images.githubusercontent.com/60236192/92127112-451b0c80-ee01-11ea-8553-56a5154c16dd.png)

**Comment by JillieBeanSim** [comment] 2020-09-03 15:38
Hello @oakmount66 I am wondering if this is a permissions issue that would deal with the RSE configuration on the host or the userId permissions itself.  The first question would be if you were the owner of the job that was to be deleted?  The next question is, if you were not the owner does the userId have the appropriate settings in the security profiles or it denies permission if a profile is not defined.  
Here is a link that can help with permissions for JES actions https://www.ibm.com/support/knowledgecenter/SSBDYH_3.1.1/com.ibm.zexpl.config.hostconfigref.doc/topics/jessecurity.html

If that is the issue we would definitely want to look into the error message being changed possibly as it does seem to point to a credential issue.

**Comment by oakmount66** [comment] 2020-09-08 12:30
Hi Billie.

Yes, I'm the owner of the job and I don't think it's an authorization issue. As you can see from the log the command is invalid. If I look here: https://www.ibm.com/support/knowledgecenter/SSLTBW_2.4.0/com.ibm.zos.v2r4.hasa200/cj.htm I don't find any $CJ commands only a $C for cancelling jobs.

/Lars.

**Comment by JillieBeanSim** [comment] 2020-09-08 12:58
@oakmount66 what version of JES do you have?

**Comment by oakmount66** [comment] 2020-09-11 13:04
Hi Billie.
My systemsprogrammer say that it follow the z/OS version. So it's v2.4
/Lars.

**Comment by JillieBeanSim** [comment] 2020-09-18 20:30
Hey @oakmount66 I was talking to a sys prog of ours and this was his advice:
" we'll need to pull their sys prog in the picture
ask to issue operator command `d opdata`  to see what the real JES subsys character is
and then ask what is coded in JMON's config file, FEJJCNFG. The sysprog can see in the JMON started task where that member resides (`CFG` invocation argument)
I'm guessing (hoping) a typo happened in FEJJCNFG
if that looks good then a JMON trace would be something good to have to see what is going on,
`F jmon,APPL=TV`
https://www.ibm.com/support/knowledgecenter/SSBDYH_3.1.1/com.ibm.zexpl.config.hostconfig.doc/topics/HCHCQS_modifyfjmon.html?pos=2
in FEJCNFG, they have to look for
`CONCHAR=$`"

**Comment by oakmount66** [comment] 2020-09-22 06:55
Hi Billie.
I think it's correct. a $ is equal to a Å large A with a circle on the top. In below picture you can see a cut from the FEJJCNFG file and its corresponding hex value.
![image](https://user-images.githubusercontent.com/60236192/93851717-eda9e700-fcb0-11ea-90ba-a13249ce51e4.png)
Best regards, Lars

**Comment by gplambert** [comment] 2020-10-09 20:33
@oakmount66 - would it be possible to send the portion of the log file for the rse delete command?  The logs for the rse commands would be located in 
`~\.zowe\imperative\logs\` and `~\.zowe\zowe\logs\` on your local machine.

**Comment by gplambert** [comment] 2020-10-21 18:12
Closing Issue since we have not been able to reproduce the problem.  If you have any updates or re-experience the issue, feel free to reopen.

**Closed by gplambert** 2020-10-21 18:12 UTC
Labels: bug
