### ISSUE TITLE
Random Links in the copybook

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#136] opened 2021-07-07 04:22 UTC
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [X] Visual Studio Code (VSCODIUM 1.57.1)
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Windows 10 Enterprise 20H2
- Java Version: java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached : no

Vscodium details: (z open editor version 1.2.1 / nodej.js 14.16.0 / Electron 12.0.7 / chrome 89.0.4389.128 )

## Problem Description

Open a PL1 source code file 

**Workspace settings:**
                                       {
                                                            "name":  "PLI",
                                                            "compilerOptions":  "NOT(^), OR(!), MARGINS(2,100)",
                                                            "language":  "pl1"
                                                        }
                                                    ],
                     "[pl1]":  {
                                   "editor.rulers":  [
                                                         0,
                                                         1,
                                                         100
                                                     ]
                               }

### Observed behavior
![issue2](https://user-images.githubusercontent.com/86772851/124700197-98ac2a00-deec-11eb-811e-65505adc844c.jpg)

This seems to appear randomly and unpredictable

**Comment by gplambert** [comment] 2021-07-07 19:24
@kraabrsg Would it be possible for you to create a simple, non-confidential example that encounters this issue?  We have not been able to reproduce.

**Comment by kraabrsg** [comment] 2021-07-08 06:25
Observed behaviour:

**include xxxxxxxx0#:**
two links are shown, to the same file xxxxxxx0%23
some errors are shown" ambigous reference to xxxxx"

xxxxx is a pointer which is declared in a copybook which is included in this one.
before this include is a pre processsor command

i cannot provide every file here (in the copybook of the copybook is another copybook included)
if you remove the propertygroups pds datasets, the links are gone, so i am not sure if the file helps to reproduce it.


My pl1 file looked like this:
![issue_links](https://user-images.githubusercontent.com/86772851/124872311-628ea900-dfc5-11eb-9dfa-375eb9520ff8.jpg)

after removing the pds in the propertygroups, saving and adding them again the links are gone


**2 Things i think could mess this up**
- # vs. %23   (translation issues ?)
- pre processor commands "%$yyyy" 


it is also difficult to reproduce, if you delete or add code or comments the links are moving around, sometimes they are gone
when deleting adding comments like described in my other issues....

I asked our security about uploading this text file, i have to wait for the answer (but i am not sure if it even helps)

**Comment by phaumer** [comment] 2021-07-08 19:46
@kraabrsg we are not able to reproduce this. Would it be possible to create a github repo with a small hello world code example that would demonstrate the issues?

**Comment by kraabrsg** [comment] 2021-07-09 09:33
@phaumer thanks for getting back on this. i really tried to make a dummy example, but it is a nightmare, sometimes it is just need to add one char to a commentline and the links are gone. But i managed to derive (somekind of luck) a dummy example. i will add this to the related issue.

**Comment by phaumer** [comment] 2022-03-14 23:59
Closing this one for now. Please, reopen if you can reproduce with Z Open Editor 2.0.0 or newer.

**Closed by phaumer** 2022-03-14 23:59 UTC
Labels: bug
